name: ai_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  provider: ^6.1.2
  flutter_bloc: ^9.0.0
  flutter_gemini: ^2.0.3
  dash_chat_2: ^0.0.21
  image_picker: ^1.1.2
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/loading3.json


